// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NureTimetableAPI.Contexts;

#nullable disable

namespace NureTimetableAPI.Migrations
{
    [DbContext(typeof(NureTimetableDbContext))]
    partial class NureTimetableDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuditoryDomainAuditoryTypeDomain", b =>
                {
                    b.Property<Guid>("AuditoriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuditoryTypesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuditoriesId", "AuditoryTypesId");

                    b.HasIndex("AuditoryTypesId");

                    b.ToTable("AuditoryDomainAuditoryTypeDomain");
                });

            modelBuilder.Entity("GroupLesson", b =>
                {
                    b.Property<Guid>("LessonDomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LessonDomainId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupLessons", (string)null);
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Domain.AuditoryDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AuditoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("HasPower")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ScheduleFetchLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("ScheduleFetchLogId");

                    b.ToTable("Auditories");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Domain.AuditoryTypeDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AuditoryTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditoryTypes");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Domain.BuildingDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Domain.DepartmentDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeachersFacultyDomainId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeachersFacultyDomainId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Domain.DirectionDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DirectionId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GroupsFacultyDomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupsFacultyDomainId");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Domain.GroupsFacultyDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GroupsFaculty");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Domain.LessonDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuditoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brief")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EndTime")
                        .HasColumnType("int");

                    b.Property<string>("GroupIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("NumberPair")
                        .HasColumnType("int");

                    b.Property<string>("ScheduleLogIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartTime")
                        .HasColumnType("int");

                    b.Property<string>("TeacherIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuditoryId");

                    b.HasIndex("TypeId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Domain.ScheduleFetchLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastFetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ScheduleFetchLogs");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Domain.TeachersFacultyDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeachersFaculties");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DirectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ScheduleFetchLogId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.HasIndex("ScheduleFetchLogId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.LessonType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdBase")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LessonTypes");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ScheduleFetchLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ScheduleFetchLogId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("TeacherLesson", b =>
                {
                    b.Property<Guid>("LessonDomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LessonDomainId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherLessons", (string)null);
                });

            modelBuilder.Entity("AuditoryDomainAuditoryTypeDomain", b =>
                {
                    b.HasOne("NureTimetableAPI.Models.Domain.AuditoryDomain", null)
                        .WithMany()
                        .HasForeignKey("AuditoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NureTimetableAPI.Models.Domain.AuditoryTypeDomain", null)
                        .WithMany()
                        .HasForeignKey("AuditoryTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupLesson", b =>
                {
                    b.HasOne("NureTimetableAPI.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NureTimetableAPI.Models.Domain.LessonDomain", null)
                        .WithMany()
                        .HasForeignKey("LessonDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Domain.AuditoryDomain", b =>
                {
                    b.HasOne("NureTimetableAPI.Models.Domain.BuildingDomain", "Building")
                        .WithMany("Auditories")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NureTimetableAPI.Models.Domain.ScheduleFetchLog", "ScheduleFetchLog")
                        .WithMany()
                        .HasForeignKey("ScheduleFetchLogId");

                    b.Navigation("Building");

                    b.Navigation("ScheduleFetchLog");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Domain.DepartmentDomain", b =>
                {
                    b.HasOne("NureTimetableAPI.Models.Domain.TeachersFacultyDomain", "TeachersFaculty")
                        .WithMany("Departments")
                        .HasForeignKey("TeachersFacultyDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeachersFaculty");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Domain.DirectionDomain", b =>
                {
                    b.HasOne("NureTimetableAPI.Models.Domain.GroupsFacultyDomain", "GroupsFaculty")
                        .WithMany("Directions")
                        .HasForeignKey("GroupsFacultyDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupsFaculty");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Domain.LessonDomain", b =>
                {
                    b.HasOne("NureTimetableAPI.Models.Domain.AuditoryDomain", "Auditory")
                        .WithMany("Lessons")
                        .HasForeignKey("AuditoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NureTimetableAPI.Models.LessonType", "Type")
                        .WithMany("Lessons")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auditory");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Group", b =>
                {
                    b.HasOne("NureTimetableAPI.Models.Domain.DirectionDomain", "Direction")
                        .WithMany("Groups")
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NureTimetableAPI.Models.Domain.ScheduleFetchLog", "ScheduleFetchLog")
                        .WithMany()
                        .HasForeignKey("ScheduleFetchLogId");

                    b.Navigation("Direction");

                    b.Navigation("ScheduleFetchLog");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Teacher", b =>
                {
                    b.HasOne("NureTimetableAPI.Models.Domain.DepartmentDomain", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NureTimetableAPI.Models.Domain.ScheduleFetchLog", "ScheduleFetchLog")
                        .WithMany()
                        .HasForeignKey("ScheduleFetchLogId");

                    b.Navigation("Department");

                    b.Navigation("ScheduleFetchLog");
                });

            modelBuilder.Entity("TeacherLesson", b =>
                {
                    b.HasOne("NureTimetableAPI.Models.Domain.LessonDomain", null)
                        .WithMany()
                        .HasForeignKey("LessonDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NureTimetableAPI.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Domain.AuditoryDomain", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Domain.BuildingDomain", b =>
                {
                    b.Navigation("Auditories");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Domain.DepartmentDomain", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Domain.DirectionDomain", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Domain.GroupsFacultyDomain", b =>
                {
                    b.Navigation("Directions");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.Domain.TeachersFacultyDomain", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("NureTimetableAPI.Models.LessonType", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
